/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#c7dde9",
        "surface-bright": "#f3faff",
        "secondary": "#1b6d24",
        "secondary-fixed-dim": "#88d982",
        "tertiary-fixed-dim": "#c4c7c9",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e0e3e5",
        "primary": "#002046",
        "on-error-container": "#93000a",
        "surface-container-low": "#e6f6ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary": "#1d2123",
        "primary-fixed-dim": "#aec7f7",
        "on-secondary-fixed": "#002204",
        "surface-container-high": "#d5ecf8",
        "primary-fixed": "#d6e3ff",
        "on-primary-container": "#87a0cd",
        "error": "#ba1a1a",
        "on-tertiary-container": "#9c9fa1",
        "on-secondary-container": "#217128",
        "inverse-primary": "#aec7f7",
        "secondary-fixed": "#a3f69c",
        "surface-variant": "#cfe6f2",
        "surface-container-highest": "#cfe6f2",
        "on-surface-variant": "#44474e",
        "on-tertiary-fixed": "#191c1e",
        "background": "#f3faff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#2e476f",
        "on-surface": "#071e27",
        "outline-variant": "#c4c6cf",
        "surface-container": "#dbf1fe",
        "inverse-surface": "#1e333c",
        "on-tertiary-fixed-variant": "#444749",
        "on-error": "#ffffff",
        "surface-tint": "#465f88",
        "primary-container": "#1b365d",
        "on-primary-fixed": "#001b3d",
        "surface": "#f3faff",
        "inverse-on-surface": "#dff4ff",
        "on-tertiary": "#ffffff",
        "outline": "#74777f",
        "on-secondary-fixed-variant": "#005312",
        "on-background": "#071e27",
        "secondary-container": "#a0f399",
        "tertiary-container": "#333638"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "container-max": "1200px",
        "unit": "4px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-sm": "8px"
      },
      "fontFamily": {
        "headline-lg": ["Public Sans"],
        "label-md": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "display-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "caption": ["Public Sans"],
        "headline-lg-mobile": ["Public Sans"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
